//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETrastornoBipolar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Individuos
    {
        public int IdIndividuo_pk { get; set; }
        public string Doc_Identidad { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string CiudadResidencia { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string CiudadNacimiento { get; set; }
        public bool Femenino { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaRegistra { get; set; }
    }
}
