//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETrastornoBipolar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Reglas_copia
    {
        public int IdRegla_pk { get; set; }
        public string Descripcion { get; set; }
        public int ParentId { get; set; }
        public int Orden { get; set; }
        public bool Femenino { get; set; }
        public bool Test { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaRegistra { get; set; }
    }
}
