//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETrastornoBipolar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RespuestasxPreguntas
    {
        public int IdRespuestaxPregunta_pk { get; set; }
        public int IdPregunta_fk { get; set; }
        public int IdOpcionRespuesta_fk { get; set; }
        public int IdPonderado_fk { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistra { get; set; }
        public bool Premisa { get; set; }
    
        public virtual TB_OpcionesRespuestas TB_OpcionesRespuestas { get; set; }
        public virtual TB_Ponderados TB_Ponderados { get; set; }
        public virtual TB_Preguntas TB_Preguntas { get; set; }
    }
}
